### ISSUE TITLE
Error with torch ReduceLROnPlateau after upgrading

### ISSUE THREAD

**Issue by GuyAglionby** [cthoyt/class-resolver#58]
I get an error importing the torch aggregation resolver, as seen in the error below. This started happening once I upgraded to torch 2.2.0 from 2.1.2

```python-traceback
Traceback (most recent call last):
  File "/home/guyaglionby/workflow/runner.py", line 10, in <module>
    from pykeen.nn.representation import TextRepresentation
  File "/opt/conda/lib/python3.10/site-packages/pykeen/nn/__init__.py", line 7, in <module>
    from . import init
  File "/opt/conda/lib/python3.10/site-packages/pykeen/nn/init.py", line 19, in <module>
    from .text import TextEncoder, text_encoder_resolver
  File "/opt/conda/lib/python3.10/site-packages/pykeen/nn/text.py", line 11, in <module>
    from class_resolver.contrib.torch import aggregation_resolver
  File "/opt/conda/lib/python3.10/site-packages/class_resolver/contrib/torch.py", line 213, in <module>
    lr_scheduler_resolver.register(ReduceLROnPlateau)
  File "/opt/conda/lib/python3.10/site-packages/class_resolver/base.py", line 170, in register
    raise RegistrationNameConflict(self, key, element, label="name")
class_resolver.base.RegistrationNameConflict: Conflict on registration of name reducelronplateau:
Existing: <class 'torch.optim.lr_scheduler.ReduceLROnPlateau'>
Proposed: <class 'torch.optim.lr_scheduler.ReduceLROnPlateau'>
```

Looks like the line that's an issue:

https://github.com/cthoyt/class-resolver/blob/e0659e3e0c850bcfc80594dc6d88ff128ff9cd40/src/class_resolver/contrib/torch.py#L213

I wonder if something like the below might fix it, but I'm not familiar enough with this library to be sure:

```python
from packaging import version
if version.parse(torch.__version__) < version.parse("2.2.0"):
    lr_scheduler_resolver.register(ReduceLROnPlateau)
```

Thanks for the library!

**Comment by mberr** [comment]
Hi @GuyAglionby ,

thanks for looking into it. This seems to be something that needs to be fixed upstream; I opened a PR here: https://github.com/cthoyt/class-resolver/pull/59

**Comment by cthoyt** [comment]
New v0.4.3 release to PyPI contains the fix https://github.com/cthoyt/class-resolver/releases/tag/v0.4.3
